### ISSUE TITLE
where does normalization for wpqr happen?

### ISSUE THREAD

**Issue by AidaSamri** [alexgkendall/caffe-posenet#14]
Hi,
the loss term in the paper is:

![loss_posenet](https://cloud.githubusercontent.com/assets/13074825/24329459/03f07376-121d-11e7-862e-ec1f9cf96305.png)

but i can't find where the q normalization happens in the code, can someone please point it out?

**Comment by AidaSamri** [comment]
@alexgkendall would you help me with this.

**Comment by wujian752** [comment]
In fact, the normalization is not used in training and it seems that removing normalization do not decrease the performance.

**Comment by wujian752** [comment]
@AidaSamri In fact, the normalization is not used in training (different with the paper) and it seems that removing normalization do not decrease the performance.

**Comment by AidaSamri** [comment]
@wujian752 Thanks for the clarification.
