### ISSUE TITLE
Test failed for the reason that "Check failed: slice_axis_ < num_axes (1 vs. 1) slice_dim out of range."

### ISSUE THREAD

**Issue by liruihao** [alexgkendall/caffe-posenet#3]
Hi, I am Ruihao, I try to test the posenet, but encounter the problem as below. 

I run "python ./posenet/scripts/test_posenet.py --model posenet/models/train_posenet.prototxt --weights posenet/models/weights_kingscollege.caffemodel --iter 346" as introduced in your readme.txt.

I0225 00:34:30.682186 13179 layer_factory.hpp:77] Creating layer data
I0225 00:34:30.682914 13179 net.cpp:106] Creating Layer data
I0225 00:34:30.682925 13179 net.cpp:411] data -> data
I0225 00:34:30.682956 13179 net.cpp:411] data -> label
I0225 00:34:30.682967 13179 data_transformer.cpp:25] Loading mean file from: posenet/kings_mean.binaryproto
I0225 00:34:30.683506 13182 db_lmdb.cpp:38] Opened lmdb posenet/posenet_kings_test_lmdb/
I0225 00:34:30.690235 13179 data_layer.cpp:41] output data size: 1,3,224,224
I0225 00:34:30.691720 13179 net.cpp:150] Setting up data
I0225 00:34:30.691746 13179 net.cpp:157] Top shape: 1 3 224 224 (150528)
I0225 00:34:30.691752 13179 net.cpp:157] Top shape: 1 (1)
I0225 00:34:30.691756 13179 net.cpp:165] Memory required for data: 602116
I0225 00:34:30.691762 13179 layer_factory.hpp:77] Creating layer slice_label
I0225 00:34:30.691776 13179 net.cpp:106] Creating Layer slice_label
I0225 00:34:30.691781 13179 net.cpp:454] slice_label <- label
I0225 00:34:30.691788 13179 net.cpp:411] slice_label -> label_xyz
I0225 00:34:30.691797 13179 net.cpp:411] slice_label -> label_wpqr
F0225 00:34:30.691809 13179 slice_layer.cpp:33] Check failed: slice_axis_ < num_axes (1 vs. 1) slice_dim out of range.
**\* Check failure stack trace: ***
Aborted (core dumped)

Could you tell me what should I do with it ? Thank you very much!

Kind regards

**Comment by alexgkendall** [comment]
It looks like you haven't quite set up the LMDB database correctly? The data layer should be outputting two blobs. Your model does output the image, 1x3x224x224. However the second top blob of the datalayer is of size 1. It should be a pose label which is a vector of size 7.

How did you form the dataset, and did you use the python script provided? `caffe-posenet/posenet/scripts/create_posenet_lmdb_dataset.py`

Cheers

**Comment by liruihao** [comment]
Thank you very much for your reply. 

I use "python ./posenet/scripts/create_posenet_lmdb_dataset.py" to create the lmdb. And all look fine. There are 1223 images in train lmdb and 346 images in test lmdb. Besides, I put the kingscollege_data in home/Documents, should I put it in "···/caffe-posenet/" file and create the lmdb file?

Regards

**Comment by alexgkendall** [comment]
Okay, the other thing that could be going wrong is that the python test script is using the standard version of Caffe (if you have this compiled on your machine). This would cause it to not correctly load the pose label. Have you modified line 13 of `test_posenet.py` to the caffe-posenet directory?

**Comment by liruihao** [comment]
I have both compiled original caffe and your caffe-posenet in my computer. Before I tested posenet, I have already modified line 13 of test_posenet.py to the caffe-posenet directory. Besides, I moved the original images of KingsCollege to caffe-posenet and create lmdb file for it. The same problem occurred. 

Regards

**Comment by liruihao** [comment]
I think it is the conflict between caffe and caffe-posenet. After I delete the build file and ./buildrelease file in caffe. I ran "python ./posenet/scripts/create_posenet_lmdb_dataset.py" in caffe-posenet workspace(where is /home/rlig/workspace/caffe-posenet).  it gave errors below:

Traceback (most recent call last):
  File "./posenet/scripts/create_posenet_lmdb_dataset.py", line 7, in <module>
    import caffe
  File "/home/rlig/workspace/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/rlig/workspace/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe



I have already change the "caffe_root = 'home/rlig/workspace/caffe-posenet/' ". Nothing works. It was also linked to 'home/rlig/workspace/caffe'.  What should I do ? Thank you very much.

Regards.

**Comment by liruihao** [comment]
Finally the problem was solved, you are right, it is the conflict between caffe and caffe-posenet. 

When I compile caffe-posenet for pycaffe, I forget to "export PYTHONPATH=/home/xxx/caffe-posenet/python:$PYTHONPATH" to "~/.bashrc", so even I have already changed caffe_root in **create_posenet_lmdb_dataset.py** and **test_posenet.py**,  the caffe python default file is in ".../caffe" not ".../caffe-posenet".

Thank you very much for your help. Your work is really inspired and impressive.

Regards

**Comment by alexgkendall** [comment]
Fantastic, thanks!

**Comment by liruihao** [comment]
Hi Alex,

I sent an email to you yesterday, but I do not know whether or not you received it.

I want to try the PoseNet within indoor scenes like Chess, Fire, Heads, Office, Pumpkin, RedKitchen and Stairs.  But after I downloaded it from Jamie Shotton's webpage, I found that there are no "train.txt" and "test.txt" files. So may I get them from you if possible? 

Kind Regards,

**Comment by alexgkendall** [comment]
Hey @liruihao, here you go:
https://github.com/alexgkendall/caffe-posenet/tree/master/posenet/7Scenes_PoseNet_TrainVal

**Comment by liruihao** [comment]
Thank you very much for sharing!

Regards,

Ruihao

**Comment by keyboardless** [comment]
@liruihao    Hi, I have the same problem like you. I have fix the problem in '.bashrc'.   I still have trouble when running "python ./posenet/scripts/test_posenet.py ...", it print out 
I0510 14:28:10.281239 14648 data_transformer.cpp:25] Loading mean file from: ../imagemean.binaryproto
F0510 14:28:10.281237 14651 db_lmdb.hpp:14] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
**\* Check failure stack trace: ***

I can't find imagemean.binaryproto in the posenet dirctory.

when I run "pyhton ./posenet/scripts/create_posenet_lmdb_dataset.py",  it create a directory named "posenet_dataset_lmdb", has 2 files : data.mdb & lock.mdb.

I question is :  what command can i get the imagemean.binaryproto file.

Thanks for your time.

attatched my script files as follow:  

[Uploading test_posenet.py.txt
[Uploading create_posenet_lmdb_dataset.py.txt…]()

**Comment by liruihao** [comment]
Hi, you should generate the mean file yourself. You can use "compute_image_mean" in "./build/tools/" to realize it.

Good luck.

**Comment by emqiongwu** [comment]
I had the same problem, both imagemean and the conflict between caffe and caffe-posenet, when I tried to run the program. Thanks for sharing the solution here!

**Comment by DRAhmadFaraz** [comment]
Dear @liruihao @keyboardless 

According to caffee instructions I have successfully installed Caffe from this repository.
When I Run this command "Python create_posenet_lmdb_dataset.py" It shiows like this.

![screenshot from 2019-01-28 10-09-06](https://user-images.githubusercontent.com/38114191/51829107-d0a6f000-22e4-11e9-9d2b-f3171e491d65.png)

After that When i use this command "python test_posenet.py --model train_kingscollege.prototxt --weights weights_kingscollege.caffemodel --iter 100" I got error of some mean file missings as shown.

![screenshot from 2019-01-28 10-11-08](https://user-images.githubusercontent.com/38114191/51829263-195ea900-22e5-11e9-8f0e-92dd149f00e0.png)

I0128 10:10:24.872309 20176 layer_factory.hpp:77] Creating layer data
I0128 10:10:24.872444 20176 net.cpp:106] Creating Layer data
I0128 10:10:24.872455 20176 net.cpp:411] data -> data
I0128 10:10:24.872473 20176 net.cpp:411] data -> label
I0128 10:10:24.872486 20176 data_transformer.cpp:25] Loading mean file from: ../imagemean.binaryproto
F0128 10:10:24.872498 20184 db_lmdb.hpp:14] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
F0128 10:10:24.872499 20176 io.cpp:54] Check failed: fd != -1 (-1 vs. -1) File not found: ../imagemean.binaryproto
*** Check failure stack trace: ***
Aborted (core dumped)

Kindly help me. I ll be thankful to you.

**Comment by DRAhmadFaraz** [comment]
@keyboardless  

u can use this command. change your directories as perspective. 

sudo /home/ahmad/Desktop/caffe-posenet/.build_release/tools/compute_image_mean /home/ahmad/Desktop/caffe-posenet/posenet/scripts/posenet_dataset_lmdb/ /home/ahmad/Desktop/caffe-posenet/posenet/imagemean.binaryproto

where the syntax is first load the compute_image_mean tool <space> input lmdb dataset path  <space> output directory.
