### ISSUE TITLE
A question about the median error in paper

### ISSUE THREAD

**Issue by FangGet** [alexgkendall/caffe-posenet#31]
Hi, this is Fang
I have a question about the median translation and rotation error stated in your paper and calculated at your code. In your test_posenet_protext, you set batch size to 40, but at your test_posenet.py, your compute median error use network output, but the compute procedure involves np.linalg.norm and np.sum , but never set axis property, so I'd like to know if you compute median error with batch size 32 or 1? as different batch size will generate different result. @alexgkendall

**Comment by DRAhmadFaraz** [comment]
@FangGet I can help you to resolve it, Have you installed this code successfully.?

**Comment by FangGet** [comment]
Thanks a lot. I'm not using this code to do the evaluation, I'm going to evaluate my own network like posenet,  and just want to know for posenet or similiar paper, which criterion or batch size they use to do the evaluation, As for this code , different batch size may output different median translation error and rotation error. @DRAhmadFaraz

**Comment by FangGet** [comment]
It's done. My mistake
