### ISSUE TITLE
Transferring weights from bvlc_googlenet

### ISSUE THREAD

**Issue by alykhantejani** [alexgkendall/caffe-posenet#5]
Hi @alexgkendall,

Firstly, great work! 

I am trying to reproduce your results (from scratch), I've just had a quick look at the prototxt files and the names of the layers are different from the bvlc_googlenet prototxt. It is my understanding that with caffe you can transfer weights to another model if the layers have the same name. 

How do you "finetune" a bvlc_googlenet model using your prototxt files?

Thanks

**Comment by alexgkendall** [comment]
Thanks Aly!

I think I used the pretrained model from Princeton.. If you scroll further down the [Caffe model zoo](https://github.com/BVLC/caffe/wiki/Model-Zoo) page you'll find it. I used the one pretrained on the Places dataset. You can download it here:
http://vision.princeton.edu/pvt/GoogLeNet/

**Comment by alykhantejani** [comment]
Thanks @alexgkendall!
