### ISSUE TITLE
How to predict one picture？

### ISSUE THREAD

**Issue by ChenhanXmu** [alexgkendall/caffe-posenet#8]
Hello,

I just want to predict an image and get its localization results rather than 300 images of prediction error in the two test python file, what should I do?

Anyone has a script?I would appreciate your help.Thank you.

**Comment by aghagol** [comment]
You must use a deploy prototxt. See this [https://github.com/alexgkendall/caffe-posenet/issues/9](https://github.com/alexgkendall/caffe-posenet/issues/9)

**Comment by ChenhanXmu** [comment]
Thanks!

**Comment by DRAhmadFaraz** [comment]
@ChenhanXmu Can u able to run this posenet to test it on one single image.?
