### ISSUE TITLE
deploy.prototxt

### ISSUE THREAD

**Issue by colegleason** [alexgkendall/caffe-posenet#9]
Hi! Do you happen to have a deploy.prototxt built for Posenet yet?

**Comment by alexgkendall** [comment]
Hey, what do you need it for? If you'd just like to run PoseNet for inference then you just need to remove the loss layers and change the data input layer to suit. 

Cheers,
Alex

**Comment by colegleason** [comment]
Hey, I just wanted to be able to run one image through the network. I made one here, like you said: https://gist.github.com/colegleason/7d4b946d69d1d188bba90299c8dc046a

**Comment by DRAhmadFaraz** [comment]
@colegleason Can you please help me to run this posenet to test it on one image.?
